### ISSUE TITLE
Psx and saturn cores being replaced with duel ram cores on update

### ISSUE THREAD

**Issue by fraggore** [funkycochise/Insert-Coin_Res#7]
For the last few weeks when i run the incert coin script on both my misters that have single ram and the analogue board it deletes the single ram satrun and psx cores and replaces them with the duel ram cores, not shore way it started to do this but just letting you know its become a problem.

**Comment by funkycochise** [comment]
Hi,
you need to change it in Scripts/#insertcoin/setup.ini

in update section you will find dualsdram option

[update]
  #dualsdram=0 ; single SDRAM core
  #dualsdram=1 ; Dual SDRAM core
  #dualsdram=2 ; Both Single and Dual SDRAM cores
  dualsdram=0

**Comment by fraggore** [comment]
just checked it is on o 
this is my setup with no changes 

[update]
  main_mister=0
  mame_rom=1
  gnw_rom=1
  console_core=1
  dualsdram=0

[console]
  psx=1
  s32x=1
  saturn=1
  sgb=1
  neogeo=1

[clean]
  console_mgl=1
  obsolete_core=1

[folder]
  folder_name="_Insert Coin"
  newest=1

**Comment by fraggore** [comment]
The one mister was missing the dualsdram=0 added it back in and ran the script and it has fixed it, yeah and the other one is ok now as well.
Thanks mate for simple fix,  i really like your script its very handy.
